#include "../tomoko.hpp"
//#include <fc/interface/interface.hpp>
#include <sfc/interface/interface.hpp>
//#include <ms/interface/interface.hpp>
//#include <md/interface/interface.hpp>
//#include <pce/interface/interface.hpp>
//#include <gb/interface/interface.hpp>
//#include <gba/interface/interface.hpp>
//#include <ws/interface/interface.hpp>
#include "interface.cpp"
#include "medium.cpp"
#include "state.cpp"
#include "utility.cpp"

#include "../icarus/heuristics/super-famicom.cpp"

#include <stdio.h>
unique_pointer<Program> program;

Program::Program(string_vector args) {
  program = this;
  Application::onMain({&Program::main, this});

  Emulator::platform = this;
  //emulators.append(new Famicom::Interface);
  emulators.append(new SuperFamicom::Interface);
  //emulators.append(new MasterSystem::MasterSystemInterface);
  //emulators.append(new MegaDrive::Interface);
  //emulators.append(new PCEngine::PCEngineInterface);
  //emulators.append(new PCEngine::SuperGrafxInterface);
  //emulators.append(new GameBoy::GameBoyInterface);
  //emulators.append(new GameBoy::GameBoyColorInterface);
  //emulators.append(new GameBoyAdvance::Interface);
  //emulators.append(new MasterSystem::GameGearInterface);
  //emulators.append(new WonderSwan::WonderSwanInterface);
  //emulators.append(new WonderSwan::WonderSwanColorInterface);

  bool gotRom = false;
  bool goFullscreen = false;
  args.takeLeft();  //ignore program location in argument parsing
  for(auto& argument : args) {
    if(argument == "--fullscreen") {
      goFullscreen = true;
    } else if(directory::exists(argument)) {
      mediumQueue.append(argument);
    } else if(file::exists(argument)) {
      //if(auto result = execute("icarus", "--import", argument)) {
      //  mediumQueue.append(result.output.strip());
      //}
      //mediumQueue.append(argument);
      //loadMedium()
      //loadMedium(*emulator[0], emulator[0]->medium);

      if(!file::exists(argument))
      {
        printf("file does not exist\n");
        continue;
      }
      if(!file::readable(argument))
      {
        printf("file is unreadable\n");
        continue;
      }

      auto buffer = file::read(argument);

      bool hasMSU1 = file::exists({argument, "msu1.rom"});
      SuperFamicomCartridge cartridge{buffer.data(), buffer.size(), hasMSU1};
      string markup;
      if(markup = cartridge.markup)
      {
        string digest = Hash::SHA256(buffer.data(), buffer.size()).digest();
        markup.append("\n");
        markup.append("information\n");
        markup.append("  region: ", cartridge.region == SuperFamicomCartridge::Region::NTSC ? "NTSC" : "PAL", "\n");
        markup.append("  title:  ", Location::prefix(argument), "\n");
        markup.append("  sha256: ", digest, "\n");
        markup.append("  note:   ", "heuristically generated by icarus\n");
      }
      else
      {
        printf("failed to parse ROM image\n");
        continue;
      }
      //printf("%s\n", markup.data());

      gotRom = true;
      romFile = argument;

      //auto document = BML::unserialize(romMarkup);
      //document["board/rom"]["name"].setValue(romFile);
      //markup = BML::serialize(document);

      romMarkup = markup;

      mediumQueue.append(argument);
    }
  }
  if(!gotRom)
  {
    printf("No ROM supplied.\n");
    Application::quit();
    return;
  }

  new Presentation;
  presentation->setVisible();

  video = Video::create(settings["Video/Driver"].text());
  video->set(Video::Handle, presentation->viewport.handle());
  video->set(Video::Synchronize, settings["Video/Synchronize"].boolean());
  if(!video->init()) video = Video::create("None");

  presentation->clearViewport();

  audio = Audio::create(settings["Audio/Driver"].text());
  audio->set(Audio::Device, settings["Audio/Device"].text());
  audio->set(Audio::Handle, presentation->viewport.handle());
  audio->set(Audio::Synchronize, settings["Audio/Synchronize"].boolean());
  audio->set(Audio::Latency, 80u);
  if(!audio->init()) audio = Audio::create("None");

  input = Input::create(settings["Input/Driver"].text());
  input->set(Input::Handle, presentation->viewport.handle());
  input->onChange({&InputManager::onChange, &inputManager()});
  if(!input->init()) input = Input::create("None");

  new InputManager;
  new SettingsManager;
  new CheatDatabase;
  new ToolsManager;
  new AboutWindow;

  presentation->setFocused();

  updateVideoShader();
  updateAudioDriver();
  updateAudioEffects();

  if(goFullscreen)
    presentation->toggleFullScreen();

  loadMedium();
}

auto Program::main() -> void {
  updateStatusText();
  inputManager->poll();
  inputManager->pollHotkeys();

  if(!emulator || !emulator->loaded() || pause || (!presentation->focused() && settings["Input/FocusLoss/Pause"].boolean())) {
    audio->clear();
    usleep(20 * 1000);
    return;
  }

  emulator->run();
}

auto Program::quit() -> void {
  hasQuit = true;
  unloadMedium();
  settings.quit();
  inputManager->quit();
  Application::quit();
}
